site_name: TigerJython in Beispielen
site_url: https://sitename.example
theme:
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  name: material
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple
  # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange  
  features:
    - content.code.copy
    - navigation.footer
  logo: assets/logo.png
  favicon: assets/favicon.ico
  language: de
dev_addr: "127.0.0.1:5500"
nav:
- "index.md"
- "rotkaeppchen.md"
- "turtle.md"
- "pixel.md"
- "linien.md"
- "shapes.md"
- "numerik.md"
- "zellautomat.md"
- "genart.md"
copyright: Copyright (<a href="https://creativecommons.org/licenses/by-sa/4.0/deed.de">CC BY-SA 4.0</a>) 2025, Jörg Kantel
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - footnotes 
extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
extra_css:
  - css/user.css
  - https://unpkg.com/katex@0/dist/katex.min.css
extra:
  generator: false